# Generated by Django 5.1.3 on 2024-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_rename_criado_em_comentario_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
