# Generated by Django 5.1.3 on 2024-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0007_alter_avaliacao_options_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='carboidratos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='fibras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='gorduras_saturadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='gorduras_totais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='sodio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1),
        ),
    ]
